# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_chat_pb2 as grpc__chat__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.try_command = channel.unary_unary(
                '/helloworld.Chat/try_command',
                request_serializer=grpc__chat__pb2.Command.SerializeToString,
                response_deserializer=grpc__chat__pb2.Response.FromString,
                )
        self.listen = channel.unary_unary(
                '/helloworld.Chat/listen',
                request_serializer=grpc__chat__pb2.User.SerializeToString,
                response_deserializer=grpc__chat__pb2.Response.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def try_command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'try_command': grpc.unary_unary_rpc_method_handler(
                    servicer.try_command,
                    request_deserializer=grpc__chat__pb2.Command.FromString,
                    response_serializer=grpc__chat__pb2.Response.SerializeToString,
            ),
            'listen': grpc.unary_unary_rpc_method_handler(
                    servicer.listen,
                    request_deserializer=grpc__chat__pb2.User.FromString,
                    response_serializer=grpc__chat__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def try_command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Chat/try_command',
            grpc__chat__pb2.Command.SerializeToString,
            grpc__chat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Chat/listen',
            grpc__chat__pb2.User.SerializeToString,
            grpc__chat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
